### PR TITLE
[Issue#136] static code analysis of the project - code formatting

### LINKED ISSUE #136: [Tests] Playwright API/E2E Test solution setup
### Playwright Tests solution
Would you be interested in having Playwright Test solution with some basic API/E2E tests added to your project? :)

### PR DESCRIPTION
**Pull request by bugITwhisperer**
## Proposed scope of change
Formatting/adjustments and fixes of all of the project files

### CODE REVIEW

**Comment by bugITwhisperer** [comment]
@lovishprabhakar : as you've most probably already noticed, this PR includes changes from https://github.com/lovishprabhakar/CSCentral-Hacktoberfest/pull/137 
I raised it separately cause I wasn't sure if you're okay with the formatting changes bein applied to all the files  
If you could please review this PR after https://github.com/lovishprabhakar/CSCentral-Hacktoberfest/pull/137 😄

**Comment by lovishprabhakar** [comment]
Good work @bugITwhisperer! Thank you for your quality contributions to CS Central. If you would like to work on an Android Project, do check out my other repository: https://github.com/lovishprabhakar/TicTacToe-Hacktoberfest 😄

**Comment by bugITwhisperer** [comment]
@lovishprabhakar : thx and the pleasure is all mine! 😸 Will check out your Android repo after working on adding some more  PW tests 

btw. just to let you know - it seems like your CSCentral repo does not follow some Hacktoberfest rules:

2023-10-12_10h33_04
2023-10-12_10h33_10

**Comment by lovishprabhakar** [comment]
Oh, thanks for letting me know about that @bugITwhisperer. I shall remove the hacktoberfest tag because once excluded I can't do anything to get my repo included back in.

**Comment by bugITwhisperer** [comment]
@lovishprabhakar : sure thing, you can remove the tag. I don't mind 😄

**Pull request merged**
